// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Addresses.Infrastructure.Migrations
{
    [DbContext(typeof(AddressesContext))]
    internal class AddressesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(
            ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation(
                    "Npgsql:ValueGenerationStrategy",
                    NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation(
                    "ProductVersion",
                    "3.1.2")
                .HasAnnotation(
                    "Relational:MaxIdentifierLength",
                    63);

            modelBuilder.Entity(
                "Addresses.Domain.AggregatesModel.Country.CountryDomain",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation(
                            "Npgsql:ValueGenerationStrategy",
                            NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");
                    b.ToTable("Countries");
                });

            modelBuilder.Entity(
                "Addresses.Domain.AggregatesModel.Province.ProvinceDomain",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation(
                            "Npgsql:ValueGenerationStrategy",
                            NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");
                    b.HasIndex("CountryId");
                    b.ToTable("Province");
                });

            modelBuilder.Entity(
                "Addresses.Domain.AggregatesModel.Province.ProvinceDomain",
                b =>
                {
                    b.HasOne(
                            "Addresses.Domain.AggregatesModel.Country.CountryDomain",
                            "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
